### ISSUE TITLE
Brand colors don't pass color contrast check

### ISSUE THREAD

**Issue by danirabbit** [artemanufrij/translit#1]
https://github.com/artemanufrij/translit/blob/9e470dde09349904682e89469d8b1dde383dba6a/data/com.github.artemanufrij.translit.appdata.xml#L20

These colors don't pass [WCAG AA](https://snook.ca/technical/colour_contrast/colour.html#fg=000000,bg=4D4D4D) contrast check

**Comment by artemanufrij** [comment]
now tested with Harvey

![screenshot from 2017-09-09 21 31 04](https://user-images.githubusercontent.com/16517095/30243279-65751bf8-95a6-11e7-8bf2-3b3de540e27c.png)
