### ISSUE TITLE
Wrong selection behaviout

### ISSUE THREAD

**Issue by Djaler** [artemanufrij/translit#2]
Steps to reproduce:
1. Type some text
2. Select it
3. Continue to type text.

Expected:
Selected text changed by new text

Actual:
New text was appended at the beginning of selected text

**Comment by artemanufrij** [comment]
hey @Djaler. Thank you for your feedback. Could you test current master branch, please?

**Comment by Djaler** [comment]
Now it works as expected, thanks

**Comment by artemanufrij** [comment]
Thank you!
