### ISSUE TITLE
Не отображается значок транслитерации

### ISSUE THREAD

**Issue by png2378** [artemanufrij/translit#4]
Не отображается значок транслитерации в заголовке окна, установлена версия 0.1.1 из AppCenter.

![](http://storage6.static.itmages.ru/i/17/0917/h_1505682751_6193405_38b5100577.png)

**Comment by artemanufrij** [comment]
Блин, опять значок только в daily ppa. :confused:

**Comment by artemanufrij** [comment]
Значок появился после последнего update elementary.
